var cards = [
    {
        id: 1,
        nameEng: 'dog',
        nameVie: 'con chó',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 2,
        nameEng: 'cat',
        nameVie: 'con mèo',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 3,
        nameEng: 'sheep',
        nameVie: 'con cừu',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 4,
        nameEng: 'cow',
        nameVie: 'con bò',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 5,
        nameEng: 'chicken',
        nameVie: 'con gà',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 6,
        nameEng: 'elephant',
        nameVie: 'con voi',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 7,
        nameEng: 'cheetah',
        nameVie: 'con báo',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 8,
        nameEng: 'horse',
        nameVie: 'con ngựa',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 9,
        nameEng: 'mouse',
        nameVie: 'con chuột',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 10,
        nameEng: 'lion',
        nameVie: 'con sư tử',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 11,
        nameEng: 'duck',
        nameVie: 'con vịt',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 12,
        nameEng: 'fish',
        nameVie: 'con cá',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 13,
        nameEng: 'turkey',
        nameVie: 'gà Tây',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 14,
        nameEng: 'goat',
        nameVie: 'con dê',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 15,
        nameEng: 'snake',
        nameVie: 'con rắn',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 16,
        nameEng: 'giraffe',
        nameVie: 'hươu cao cổ',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 17,
        nameEng: 'turtle',
        nameVie: 'con rùa',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 18,
        nameEng: 'monkey',
        nameVie: 'con khỉ',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 19,
        nameEng: 'bear',
        nameVie: 'con gấu',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 20,
        nameEng: 'fox',
        nameVie: 'con cáo',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 21,
        nameEng: 'squirrel',
        nameVie: 'con sóc',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 22,
        nameEng: 'raccoon',
        nameVie: 'gấu mèo',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 23,
        nameEng: 'alligator',
        nameVie: 'cá sấu',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 24,
        nameEng: 'wolf',
        nameVie: 'chó sói',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 25,
        nameEng: 'bat',
        nameVie: 'con dơi',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 26,
        nameEng: 'deer',
        nameVie: 'con hươu',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 27,
        nameEng: 'dolphin',
        nameVie: 'cá heo',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 28,
        nameEng: 'shark',
        nameVie: 'cá mập',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 29,
        nameEng: 'whale',
        nameVie: 'cá voi',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 30,
        nameEng: 'hermit crab',
        nameVie: 'ốc mượn hồn',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 31,
        nameEng: 'penguin',
        nameVie: 'chim cánh cụt',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 32,
        nameEng: 'bee',
        nameVie: 'con ong',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 33,
        nameEng: 'camel',
        nameVie: 'lạc đà',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 34,
        nameEng: 'scorpion',
        nameVie: 'bọ cạp',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 35,
        nameEng: 'donkey',
        nameVie: 'con lừa',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 36,
        nameEng: 'jellyfish',
        nameVie: 'con sứa',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 37,
        nameEng: 'octopus',
        nameVie: 'bạch tuộc',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 38,
        nameEng: 'starfish',
        nameVie: 'sao biển',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 39,
        nameEng: 'stingray',
        nameVie: 'cá đuối',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
    {
        id: 40,
        nameEng: 'panda',
        nameVie: 'gấu trúc',
        imgURL: '',
        audioURL: '',
        phonetic: '',
    },
];